#!/usr/bin/env spang2
# @endpoint https://spang.dbcls.jp/sparql
# @input (9606) (10090) (10116)

SELECT ?id ?label
WHERE {
  VALUES (?id) { {{INPUT}} }
  BIND(URI(CONCAT('http://identifiers.org/taxonomy/', $id)) AS ?taxid)
  ?taxid rdfs:label ?label .
}
