#!/usr/bin/env spang2
# @endpoint test
# @param pattern=Homo
# @option -a

SELECT DISTINCT ?class ?label
WHERE {
  ?class a owl:Class ;
      rdfs:label ?label .
  ?label bif:contains "{{pattern}}" .
}
